### ISSUE TITLE
Embedded Solr requires apache logging

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#1]
Fixed by adding the dependency to the pom file in EmbededSolr/pom.xml

``` java
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
    at org.apache.http.impl.client.CloseableHttpClient.<init>(CloseableHttpClient.java:60)
    at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:271)
    at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:127)
    at org.apache.http.impl.client.SystemDefaultHttpClient.<init>(SystemDefaultHttpClient.java:116)
    at org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(HttpClientUtil.java:117)
    at org.apache.solr.handler.component.HttpShardHandlerFactory.init(HttpShardHandlerFactory.java:165)
    at org.apache.solr.handler.component.ShardHandlerFactory.newInstance(ShardHandlerFactory.java:49)
    at org.apache.solr.core.CoreContainer.load(CoreContainer.java:211)
    at gov.nih.nlm.ncbi.seqr.SeqrApp.main(SeqrApp.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more
```

**Comment by averagehat** [comment]
Closed 7d76985f03
