### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by nabihlme** [DCGenomics/seqr#12]
When I run Seqr -h, I get the help info twice and:

net.sourceforge.argparse4j.internal.HelpScreenException: Help Screen
    at net.sourceforge.argparse4j.impl.action.HelpArgumentAction.run(HelpArgumentAction.java:53)
    at net.sourceforge.argparse4j.internal.ArgumentImpl.run(ArgumentImpl.java:469)
    at net.sourceforge.argparse4j.internal.ArgumentParserImpl.processArg(ArgumentParserImpl.java:935)
    at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:828)
    at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:699)
    at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:593)
    at net.sourceforge.argparse4j.internal.ArgumentParserImpl.parseArgs(ArgumentParserImpl.java:586)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

(I changed line 65 to give the full stack trace for a second...)

**Comment by averagehat** [comment]
I haven't been able to recreate this.

**Comment by nabihlme** [comment]
As far as I can tell, argparse4j always throws a HelpScreenException when asked to display help. 

https://github.com/tatsuhiro-t/argparse4j/blob/master/src/main/java/net/sourceforge/argparse4j/impl/action/HelpArgumentAction.java

I added another catch to exit gracefully when this happens.
commit: eef2c40f1af76cae6acf8e17c96314d97f472e62
If it truly can't be recreated by you guys, just remove that additional catch block.

**Comment by averagehat** [comment]
Looks good, thanks Nathan.
