### ISSUE TITLE
SeqrApp Exception (file names)

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#2]
This is what happens when I run SeqApp.java in the embeddedsolr subproject:

``` java

Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
    at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:478)
    at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:454)
    at gov.nih.nlm.ncbi.seqr.SeqrApp.main(SeqrApp.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by averagehat** [comment]
This doesn't work even including the data directory on EC2 under testdata/data.
It is strange because I don't know where `Parameter 'directory'` is coming from

**Comment by averagehat** [comment]
@lianyi  
This might just be a problem on my end, because I don't see how the new `pom.xml` file could have caused this. 

``` java

michaelpanciera@michaelpanciera-Lenovo-Z580:~/clones/seqr_hackathon_v002/EmbededSolr$ mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building EmbededSolr 4.10.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ embeded-solr ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/michaelpanciera/clones/seqr_hackathon_v002/EmbededSolr/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ embeded-solr ---
[INFO] Compiling 1 source file to /home/michaelpanciera/clones/seqr_hackathon_v002/EmbededSolr/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.524s
[INFO] Finished at: Mon Aug 03 17:07:16 EDT 2015
[INFO] Final Memory: 10M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project embeded-solr: Compilation failure: Compilation failure:
[ERROR] /home/michaelpanciera/clones/seqr_hackathon_v002/EmbededSolr/src/main/java/gov/nih/nlm/ncbi/seqr/SeqrApp.java:[40,18] error: generics are not supported in -source 1.3
[ERROR] 
[ERROR] (use -source 5 or higher to enable generics)
[ERROR] /home/michaelpanciera/clones/seqr_hackathon_v002/EmbededSolr/src/main/java/gov/nih/nlm/ncbi/seqr/SeqrApp.java:[44,23] error: enhanced for loops are not supported in -source 1.3
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by averagehat** [comment]
This is a problem with my setup

**Comment by averagehat** [comment]
@lianyi 
This problem came back:

``` java

Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
    at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:460)
    at gov.nih.nlm.ncbi.seqr.SeqrApp.main(SeqrApp.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by averagehat** [comment]
This is because the working directory is the project root by default while `testdata/data` is within the submodule root (ie EmbeddedSolr/testdata)

**Comment by lianyi** [comment]
That's good to know. Perhaps we can make this directory configurable since we are making this a commandline option.
