### ISSUE TITLE
build failure @ robot

### ISSUE THREAD

**Issue by lianyi** [DCGenomics/seqr#40]
``` log
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.251s
[INFO] Finished at: Tue Sep 08 11:31:32 EDT 2015
[INFO] Final Memory: 57M/761M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.robotframework:robotframework-maven-plugin:1.4.5:run (default) on project seqr: 2 critical test cases failed. Check the logs for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by lianyi** [comment]
the issue is the target/seqr._.jar was build during the package phase. The robot do not have the fresh build seqr._.jar during the "test" phase.  One way is to separate the "mvn robotframework:run" out of the "mvn test", after "mvn package". For now, we can also run it manually

```
mvn robotframework:run
```

**Comment by averagehat** [comment]
Why did [this build](https://travis-ci.org/NCBI-Hackathons/seqr/builds/78666679) pass, in that case?
I'm not sure that's the problem.

**Comment by lianyi** [comment]
Perhaps it shouldn't? The following messages seem unexpected. 

```
org.apache.solr.common.SolrException: No such core: sequence
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:112)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:72)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:45)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.search(SeqrController.java:120)
    at gov.nih.nlm.ncbi.seqr.Seqr.handleCommand(Seqr.java:365)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:82)
org.apache.solr.common.SolrException: No such core: sequence
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:112)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:72)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:45)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.search(SeqrController.java:120)
    at gov.nih.nlm.ncbi.seqr.Seqr.handleCommand(Seqr.java:365)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:82)
org.apache.solr.common.SolrException: No such core: sequence
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:112)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:72)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:45)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.search(SeqrController.java:120)
    at gov.nih.nlm.ncbi.seqr.Seqr.handleCommand(Seqr.java:365)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:82)
org.apache.solr.common.SolrException: No such core: sequence
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:112)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:72)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:45)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.search(SeqrController.java:120)
    at gov.nih.nlm.ncbi.seqr.Seqr.handleCommand(Seqr.java:365)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:82)
org.apache.solr.common.SolrException: No such core: sequence
    at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:112)
    at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
    at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:301)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:72)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.makeQuery(SeqrController.java:45)
    at gov.nih.nlm.ncbi.seqr.solr.SeqrController.search(SeqrController.java:120)
    at gov.nih.nlm.ncbi.seqr.Seqr.handleCommand(Seqr.java:365)
    at gov.nih.nlm.ncbi.seqr.Seqr.main(Seqr.java:82)
```

**Comment by lianyi** [comment]
closing this issue for now. The build on master working as expected.
