### ISSUE TITLE
Solr Plugin init error

### ISSUE THREAD

**Issue by averagehat** [DCGenomics/seqr#9]
``` java
        EmbeddedSolrServer solrServer = new EmbeddedSolrServer(container, "sequence");
        gov.nih.nlm.ncbi.seqr.SeqrController control = new gov.nih.nlm.ncbi.seqr.SeqrController(solrServer);
        control.loadJSONDir("testdata/data");
```

gives

``` java

Caused by: org.apache.solr.common.SolrException: Could not load conf for core sequence: Plugin init failure for [schema.xml] fieldType "matchstring_tanimoto": Error loading class 'org.apache.lucene.analysis.tanimoto.OverlapSimilarity'. Schema file is /home/michaelpanciera/clones/seqr_hackathon_v002/testdata/solr/sequence/conf/schema.xml
    at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:489)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "matchstring_tanimoto": Error loading class 'org.apache.lucene.analysis.tanimoto.OverlapSimilarity'. Schema file is /home/michaelpanciera/clones/seqr_hackathon_v002/testdata/solr/sequence/conf/schema.xml
    at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:595)
    at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166)
    at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
    at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69)
    at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:90)
    at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:62)
    ... 7 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "matchstring_tanimoto": Error loading class 'org.apache.lucene.analysis.tanimoto.OverlapSimilarity'
    at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:177)
    at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:486)
    ... 12 more
Caused by: org.apache.solr.common.SolrException: Error loading class 'org.apache.lucene.analysis.tanimoto.OverlapSimilarity'
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:490)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:521)
    at org.apache.solr.schema.IndexSchema.readSimilarity(IndexSchema.java:950)
    at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:100)
    at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:43)
    at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:151)
    ... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.tanimoto.OverlapSimilarity
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:810)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:474)
    ... 18 more
```

**Comment by averagehat** [comment]
fixed in #10
